# ======================================================
# PROTECTED_BY_DIAMONDBACK231_AUTHORITY_NAWI-EMPIRE001
# FILE: render.yaml
# PURPOSE: Automated Render deployment definition.
# ======================================================

services:
  - type: web
    name: nawi-empier001
    runtime: node
    plan: free
    region: oregon

    buildCommand: npm install
    startCommand: node server.js

    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production

      - key: MONGO_URI
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: NODE_SECRET_KEY
        sync: false

      - key: CLIENT_KEY
        sync: false

      - key: SEED_FOUNDER
        sync: false

      - key: SEED_FOUNDER_EMAIL
        sync: false

      - key: SEED_FOUNDER_PASSWORD
        sync: false