# ======================================================
# protected_by_diamondback231_authority_nawi-empire001
# file: render.yaml
# purpose: automated cluster deployment definition.
# description: official blueprint for nawi-empire001 deployment.
# ======================================================

version: "1"
services:
  - type: web
    name: nawi-empire001
    runtime: node
    plan: free
    region: oregon
    buildcommand: npm install
    startcommand: node server.js
    autodeploytrigger: commit
    envvars:
      - key: client_key
        sync: false
      - key: seed_founder_password
        sync: false
      - key: seed_founder_email
        sync: false
      - key: seed_founder
        sync: false
      - key: node_secret_key
        sync: false
      - key: node_env
        sync: false
      - key: jwt_secret
        sync: false
      - key: mongo_uri
        sync: false
